### ISSUE TITLE
Göra klart papprena för Just Developments Nyemission

### ISSUE THREAD

**Issue by niklasrudemo** [niklasrudemo/webdevfinal#6]

**Comment by niklasrudemo** [comment]
### Todos

- [ ] Uppdatera dokument inför bolagsstämman 2017-10-30
- [ ] Kolla med Bolagsverket om man kan lämna in med Scrive underskrift
- [ ] Skicka ut för underskrift i Scrive
- [ ] Skicka in till Bolagsverket
- [ ] Upprätta skuldebrev och få dem underskrivna
- [ ] Fakturera
